### PR TITLE
feat(lsp): handle user configuration in setup()

### LINKED ISSUE #1697: [Feature]: User override of LSP configurations
### Feature motivation

It would be nice to have a mechanism to use the `lsp.manager` to load a user-provided table into the LSP configuration.

The current mechanism of using the `lvim.lsp.override` does two things:
1. Removes the default lazy installation of the LS.
2. Removes the default configurations from `providers`.

For some user configuration changes, it might be good to retain (1) and just change (2). The current override mechanism sort of just nukes everything.

### Describe the expected solution

1. Define a user config table like `lvim.lsp.user_ls_config.<servername>`.
2. Have `lsp.manager.setup()` accept a user config table and force `tbl_deep_extend()` the  config like it does below for the default config: https://github.com/LunarVim/LunarVim/blob/7a939ad771403e20341c9465af66573d225300bb/lua/lsp/manager.lua#L56-L65

Some plugins also provide configuration parameters to the LSs to work (e.g., https://github.com/jakewvincent/texmagic.nvim). It might be nice to have (2) happen after the plugins load, and use lambdas in `lvim.lsp.user_ls_config.<servername>` to configure the servers correctly.

### Describe the alternatives you've considered

The only alternative now is to install the overridden servers manually. This is what I am using right now (based on  @abzcoding's overridden LSP loading style from [here](https://github.com/abzcoding/lvim/blob/8cb8e7e2bb3d2f65c8b6e6bcff24eb35ae993711/config.lua#L53-L55)). But this installs the server the first time the `config.lua` file is read. 

It might be possible to combine this with `autocmd`s to get the necessary result. But that seems like replicating effort, as the `lsp.manager.setup()` and the code above is almost identical. Also, for servers that are reused across multiple FTs (e.g. tailwind), this is just not ergonomic as it would mean having to find the relevant FTs. 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kylo252**
# Description

- allow passing user configuration directly when calling `require('lsp.manager').setup("myserver", myopts)`. 
These options will take precedence over any pre-existing default configuration.
- allow calling the setup function for servers not supported yet by "nvim-lsp-installer"

Fixes #1697

## How Has This Been Tested?

You can try this simple test

```lua
lvim.lsp.on_init_callback = function ()
  print("hello")
end

require("lsp.manager").setup("stylelint_lsp", {
	on_attach = function()
		print("world")
	end,
})
```

You can also test a server that's not supported by "nvim-lsp-installer"

### CODE REVIEW

**Comment by xeluxee** [comment]
I tried to put this in `config.lua` but it doesn't work

``` lua
require("lsp.manager").setup("clangd", {
  on_attach = function() print("clangd on_attach") end,
})
```

**Comment by abzcoding** [comment]
> I tried to put this in `config.lua` but it doesn't work
> 
> ```lua
> require("lsp.manager").setup("clangd", {
>   on_attach = function() print("clangd on_attach") end,
> })
> ```

can you try this instead?
```lua
lvim.lsp.on_init_callback = function ()
  require("lsp.manager").setup("clangd", {
    on_attach = function() print("clangd on_attach") end,
  })
end
```

**Comment by xeluxee** [comment]
> 
> can you try this instead?
> 
> ```lua
> lvim.lsp.on_init_callback = function ()
>   require("lsp.manager").setup("clangd", {
>     on_attach = function() print("clangd on_attach") end,
>   })
> end
> ```

@abzcoding it works but two language servers get attached to a single buffer

**Comment by abzcoding** [comment]
> > can you try this instead?
> > ```lua
> > lvim.lsp.on_init_callback = function ()
> >   require("lsp.manager").setup("clangd", {
> >     on_attach = function() print("clangd on_attach") end,
> >   })
> > end
> > ```
> 
> @abzcoding it works but two language servers get attached to a single buffer

can you run `:LvimInfo` and `:LspInfo`

**Comment by xeluxee** [comment]
Ok I've blacklisted clangd but now no client can't be attached.
My config in `config.lua`:
``` lua
lvim.lsp.automatic_servers_installation = false
lvim.lsp.override = {"clangd"}
lvim.lsp.on_init_callback = function()
  require("lsp.manager").setup("clangd", {
    cmd = {"clangd", "--background-index", "--header-insertion=never", "--cross-file-rename"},
  })
end
```

**Comment by abzcoding** [comment]
maybe there is a better way for blacklisting, i'm a bit out of the loop though
 @kylo252 might be able to help

**Comment by kylo252** [comment]
Oops I forgot that this isn't configurable: 
https://github.com/LunarVim/LunarVim/blob/85e7b7804a2c9d6847ff978c82bb3a3ac16d757f/lua/lsp/templates.lua#L18-L24

Feel free to open a ticket about it, and hopefully a PR!

Otherwise just delete that folder/file or point the `lvim.lsp.templates_dir` variable somewhere where you can have it version controlled so you don't lose your changes.

**Pull request merged**
