### PR TITLE
change nvim to nvcode

### PR DESCRIPTION
**Pull request by mjcc30**

### CODE REVIEW

**Comment by ChristianChiarulli** [comment]
This looks great so far. I've really been having an issue where the auto installer will fail with:

`+PackerInstall` due to `UpdatePlugins` not being recognized

The other thing is that I need all of my plugins to go into the `opt` directory, so they're not sourced automatically when someone uses vanilla nvim.
 
Thanks for working on this.

**Comment by mjcc30** [comment]
Hello Thanks for you work !
i'm french web developer and i'm using nvcode everyday at work, i also learning lua and want to contribute.
Sorry for the mergoing request i'm not familiar with github, can you please make a video to explain how to fork the project and contribute that could help ?

**Comment by ChristianChiarulli** [comment]
This should be fine but I can put a video out on it later, have you tested that the script works?

**Comment by mjcc30** [comment]
i created a new branch with my script that we can easily maintain. I readapt this script to be more convenient to understand

**Pull request closed without merging**
