### PR TITLE
feat: support select and operator mode keymaps

### PR DESCRIPTION
**Pull request by kylo252**
# Description

- support select mode keymap
- support operator mode keymap
- update which-key settings

### CODE REVIEW

**Comment by abzcoding** [comment]
> Why are visual mode and visual block mode renamed? 'x' has definitively been Visual Block Mode as far as I've known vim, same with 'v' being Visual Mode.

i do agree with you though, it feels a bit weird

**Comment by kylo252** [comment]
I was also skeptical the first time I saw it, but it's actually in the friendly [manual](https://neovim.io/doc/user/map.html#mapping):
```doc
1.4 LISTING MAPPINGS					*map-listing*

When listing mappings the characters in the first two columns are:

      CHAR	MODE	
     <Space>	Normal, Visual, Select and Operator-pending
	n	Normal
	v	Visual and Select
	s	Select
	x	Visual
	o	Operator-pending
	!	Insert and Command-line
	i	Insert
	l	":lmap" mappings for Insert, Command-line and Lang-Arg
	c	Command-line
	t	Terminal-Job
```

**Comment by chase** [comment]
> I was also skeptical the first time I saw it, but it's actually in the friendly [manual](https://neovim.io/doc/user/map.html#mapping):

Huh, I just associated it with the mode and not the mapping intent!

Although this is a breaking change, maybe keep the originals around so as not to break things but only keep the changes around in documentation?

**Comment by kylo252** [comment]
Let's leave this alone for now, we can revisit it later.

**Pull request closed without merging**
