### PR TITLE
[Feature] use structlog and notify.nvim

### PR DESCRIPTION
**Pull request by kylo252**
# Description

A much better logging experience all around.

### CODE REVIEW

**Comment by Tastyep** [comment]
> I was also wondering how easy would it be to _optionally_ relegate the console responsibility to this plugin: https://github.com/rcarriga/nvim-notify
> 
> notify
> 
> Which I believe that @abzcoding will be very much in favor of smile

This looks great ! It should be easily achievable by providing a new sink.
I could either provide it directly from structlog or you could implement it yourself here. Since the logger is already specialized for nvim I don't mind adding it to structlog.

**Comment by kylo252** [comment]
> This looks great ! It should be easily achievable by providing a new sink. I could either provide it directly from structlog or you could implement it yourself here. Since the logger is already specialized for nvim I don't mind adding it to structlog.

Oh I didn't even think about adding it a sink. I set out to add it but got stuck in the step with specifiying the log level. 

<details>
<summary>Notify handler</summary>

```lua
--- Sends log entries to Notify.

--- The Notify sink class.
-- @type Notify
local Notify = {}

--- Create a new Notify handler
-- @function Notify
-- @param opts Optional parameters
-- @param opts.timeout Number of milliseconds to show the window, default: 5000
-- @param opts.stages Animation stages, default "fade_in_slide_out"
-- @param opts.background_colour Highlight group, default: Normal
-- @param opts.icons Icons used for earch log level
setmetatable(Notify, {
  __call = function(cls, ...)
    return cls:new(...)
  end,
})

function Notify:new(opts)
  opts = opts or {}

  local notify = require("notify").setup(opts)

  Notify.__index = Notify
  setmetatable(notify, Notify)

  return Notify
end

function Notify:send(msg, level, opts)
end

return Notify
```

</details>

I don't think it's gonna work as a sink with the current abstraction level that you have in Structlog, because it needs more metadata and should be higher up in the pipeline anyway.

> A sink is the final output of your logs entries. Once they have been through the pipeline of log processors and formatter, the final result is sent to the sink.

**Comment by abzcoding** [comment]
am i supposed to get this when there is an error in my config?
Screen Shot 2021-10-20 at 8 26 40 PM

**Comment by abzcoding** [comment]
> > other than that it looks very good tyvm 👍
> 
> Did you update structlog? I had another issue that was still related to that.

let me try it again

**Pull request merged**
